import { useEffect, useRef, useState } from "react";

import type {
  Message,
  SessionEntry,
  Product,
  BackendResponse,
  CanonicalProduct,
    LoadingContent,
  Card,
} from "@/types";

import { clearSession, scrapeProducts, searchProducts } from "@/services/api";
import { normalizeProducts } from "@/utils/normalizeProducts";

const isGreetingText = (text: string) => {
  const words = text.toLowerCase().replace(/[^a-z\s]/g, " ").split(/\s+/).filter(Boolean)
  if (!words.length || words.length > 6) return false
  const greetingWords = new Set(["hi", "hai", "hello", "hey", "yo", "sup", "namaste", "namaskar"])
  const politeWords = new Set(["there", "everyone", "friend", "good", "morning", "afternoon", "evening", "day"])
  return words.some((word) => greetingWords.has(word)) && words.every((word) => greetingWords.has(word) || politeWords.has(word))
}

/* Removed fixed exploratory filter options. Filters now come from the backend. 
  const genericGroups = [
    { name: "Budget", options: ["Under ₹10,000", "₹10,000–₹25,000", "₹25,000–₹50,000", "₹50,000–₹1,00,000", "No fixed budget"] },
    { name: "Priority", options: ["Best value", "Best quality", "Lowest price", "Best features", "Fast delivery"] },
    { name: "Brand", options: ["Any brand", "Samsung", "Apple", "Sony", "Philips", "Xiaomi", "Dell"] },
    { name: "Color", options: ["Any color", "Black", "White", "Silver", "Blue", "Red"] },
    { name: "Use case", options: ["Daily use", "Work", "Home", "Travel", "Entertainment", "No preference"] },
  ]

  return {
    type: "filters",
    title: `Customize your ${category || "product"}`,
    description: "Choose any details you know. Everything is optional; we can search with smart defaults.",
    groups: genericGroups,
    show_search: true,
    search_placeholder: `Or search for a specific ${category || "product"}...`,
    submit_button: "Search with these preferences",
  }
*/

export function useChat() {
  const [query, setQuery] = useState("")
  // Full chat transcript for the active session.
  const [messages, setMessages] = useState<Message[]>([])
  // Whether a backend request is currently in flight (disables input, shows typing indicator).
  const [isLoading, setIsLoading] = useState(false)
  // Rich loading-state content (title/description/tip) generated by the LLM
  // alongside canonical_product on the parsed_query/ready response. Shown
  // in place of the plain three-dot spinner while /scrape is running, since
  // that's the actual long wait. Empty strings fall back to the plain dots.
  const [loadingContent, setLoadingContent] = useState<LoadingContent>({})
  const [loadingStage, setLoadingStage] = useState(0)
  // Backend session identifier; regenerated whenever the user starts a new search,
  // so the backend's conversational state resets cleanly.
  const [sessionId, setSessionId] = useState(() => `session_${Date.now()}`)
  // List of recent search sessions shown in the left sidebar (most recent first, capped at 9).
  const [sessions, setSessions] = useState<SessionEntry[]>([])
  // The query string of whichever session is currently active/displayed.
  const [activeSession, setActiveSession] = useState<string | null>(null)
  // Collapsed/expanded state for the right filter sidebar.
  const [sidebarCollapsed, setSidebarCollapsed] = useState(false)
  // Collapsed/expanded state for the left recent-searches sidebar.
  const [recentCollapsed, setRecentCollapsed] = useState(false)
  // The resolved product/search label shown in the top header bar.
  const [activeProductLabel, setActiveProductLabel] = useState<string | null>(null)
  const messagesScrollRef = useRef<HTMLDivElement>(null)

  // Ref to the main text input, used to refocus it after starting a new search.
  const inputRef = useRef<HTMLInputElement>(null)

  const startLoadingProgress = (content: LoadingContent, startStage = 0) => {
    setLoadingContent(content)
    setLoadingStage(startStage)

    return setInterval(() => {
      setLoadingStage((prev) => (prev >= 4 ? prev : prev + 1))
    }, 1200)
  }

  const stopLoadingProgress = (progress?: ReturnType<typeof setInterval>) => {
    if (progress) clearInterval(progress)
    setLoadingContent({})
    setLoadingStage(0)
  }

  // Very fast deterministic greetings can otherwise resolve before React paints
  // the loading card. Keep the visual state consistent with the LLM path.
  const waitForGreetingLoading = async (text: string) => {
    const isGreeting = isGreetingText(text)
    if (isGreeting) await new Promise((resolve) => setTimeout(resolve, 550))
  }

  const getInitialLoadingContent = (text: string): LoadingContent => {
    const isGreeting = /^(hi+|he+y+|hello+|hey+|yo+|sup|namaste|namaskar)[!,.\s]*$/i.test(text.trim())

    if (isGreeting) {
      return {
        title: "Getting your shopping assistant ready...",
        description: "I’m preparing a quick way for you to start finding the right product.",
        tip: "Tell me what you want to buy whenever you’re ready, and I’ll compare the best options.",
      }
    }

    return {
      title: "Understanding your request...",
      description: "I’m identifying the product and preferences that matter most to you.",
      tip: "Adding a budget, brand, or must-have feature helps narrow down the best options.",
    }
  }

  useEffect(() => {
    const container = messagesScrollRef.current
    if (!container) return

    container.scrollTo({
      top: container.scrollHeight,
      behavior: "smooth",
    })
  }, [messages, isLoading])

  useEffect(() => {
    if (!activeSession || messages.length === 0) return
    const saveId = window.setTimeout(() => {
      setSessions((prev) =>
        prev.map((s) => (s.query === activeSession ? { ...s, messages } : s)),
      )
    }, 0)

    return () => window.clearTimeout(saveId)
  }, [messages, activeSession])

  const buildDealRecommendation = (products: Product[]) => {
    const pricedProducts = products.filter((product) => Number(product.priceinr) > 0)
    if (pricedProducts.length === 0) return ""

    const bestDeal =
      pricedProducts.find((product) => product.isbestprice) ||
      [...pricedProducts].sort((a, b) => Number(a.priceinr) - Number(b.priceinr))[0]

    const store = bestDeal.store || "this store"
    const price = Number(bestDeal.priceinr).toLocaleString("en-IN")
    const originalPrice = Number(bestDeal.originalprice)
    const savings = originalPrice > Number(bestDeal.priceinr)
      ? originalPrice - Number(bestDeal.priceinr)
      : 0
    const savingsText = savings > 0
      ? ` You save ₹${savings.toLocaleString("en-IN")}${bestDeal.discountpercent ? ` (${bestDeal.discountpercent}% off)` : ""} compared with its listed price.`
      : ""
    const dealText = bestDeal.isbestprice
      ? "It has the best available price among the options found."
      : "It is the lowest-priced option among the products found."

    return `**Recommendation: Buy from ${store} for ₹${price}.** ${dealText}${savingsText}`
  }

  const handleProductAction = (products: Product[], action: "compare" | "cheapest" | "rated" | "delivery") => {
    const available = products.filter((product) => Number(product.priceinr) > 0)
    if (!available.length) return

    const byPrice = [...available].sort((a, b) => Number(a.priceinr) - Number(b.priceinr))
    const bestRated = [...available].sort((a, b) => Number(b.rating || 0) - Number(a.rating || 0))[0]
    const productLabel = (product: Product) => product.productname || product.title || product.store || "this option"
    const priceLabel = (product: Product) => `₹${Number(product.priceinr).toLocaleString("en-IN")}`
    let content = ""

    if (action === "cheapest") {
      content = `**Cheapest option:** ${productLabel(byPrice[0])} on ${byPrice[0].store || "the listed store"} for ${priceLabel(byPrice[0])}.`
    } else if (action === "rated") {
      content = `**Best-rated option:** ${productLabel(bestRated)}${bestRated.rating ? ` — rated ${bestRated.rating.toFixed(1)}/5` : ""}${bestRated.priceinr ? ` at ${priceLabel(bestRated)}` : ""}.`
    } else if (action === "delivery") {
      const withDelivery = available.find((product) => product.deliverylabel)
      content = withDelivery
        ? `**Delivery option:** ${productLabel(withDelivery)} has ${withDelivery.deliverylabel}.`
        : "Delivery timing is not available in the current store results."
    } else {
      content = `**Quick comparison:** ${byPrice.map((product) => `${product.store || "Store"}: ${priceLabel(product)}`).join(" • ")}. ${buildDealRecommendation(available)}`
    }

    setMessages((prev) => [...prev, { role: "assistant", content }])
  }

  const getContextualReply = (text: string) => {
    const lastProducts = [...messages].reverse().find((message) => message.products?.length)?.products
    if (!lastProducts?.length) return null

    const question = text.toLowerCase().trim()
    const available = lastProducts.filter((product) => Number(product.priceinr) > 0)
    if (!available.length) return null

    const byPrice = [...available].sort((a, b) => Number(a.priceinr) - Number(b.priceinr))
    const byRating = [...available].sort((a, b) => Number(b.rating || 0) - Number(a.rating || 0))
    const label = (product: Product) => product.productname || product.title || product.store || "this option"
    const price = (product: Product) => `₹${Number(product.priceinr).toLocaleString("en-IN")}`

    if (/(cheapest|lowest price|less expensive)/.test(question)) {
      return `**Cheapest option:** ${label(byPrice[0])} on ${byPrice[0].store || "the listed store"} for ${price(byPrice[0])}.`
    }
    if (/(best rated|highest rated|rating)/.test(question)) {
      return `**Best-rated option:** ${label(byRating[0])}${byRating[0].rating ? ` — ${byRating[0].rating.toFixed(1)}/5` : ""}, priced at ${price(byRating[0])}.`
    }
    if (/(delivery|arrive|fastest)/.test(question)) {
      const deliveryOption = available.find((product) => product.deliverylabel)
      return deliveryOption
        ? `**Delivery:** ${label(deliveryOption)} lists ${deliveryOption.deliverylabel}.`
        : "The current results do not include delivery timing."
    }
    if (/(compare|amazon|flipkart|which one|which is better|worth buying|worth it|recommend)/.test(question)) {
      const comparison = byPrice.map((product) => `${product.store || "Store"}: ${price(product)}`).join(" • ")
      return `**Based on the products currently shown:** ${comparison}. ${buildDealRecommendation(available)} Ratings and delivery details are shown where each store provided them.`
    }

    return null
  }

  const replaceTemporaryMessage = (newMessage: Message) => {
    // Loading is rendered separately. When a user submits a filter card,
    // replace the consumed filter card with the backend's consolidated card
    // instead of displaying one clarification card per turn.
    setMessages((prev) => {
      const hasFilterCard = newMessage.cards?.some((card) => card.type === "filters")
      if (!hasFilterCard) return [...prev, newMessage]

      const previousFilterIndex = [...prev]
        .map((message, index) => ({ message, index }))
        .reverse()
        .find(({ message }) =>
          message.role === "assistant" &&
          message.optionUsed === true &&
          message.cards?.some((card) => card.type === "filters"),
        )?.index

      if (previousFilterIndex === undefined) return [...prev, newMessage]

      return prev.map((message, index) =>
        index === previousFilterIndex ? newMessage : message,
      )
    })
  };

  /**
   * Shared response-type handling, used by both handleSend (typed chat) and
   * handleFilterSearch (chip/filter/search-box submissions). Keeping this in
   * one place means both paths render parsed_query / conversation / results /
   * products responses identically — only how the *request* is made differs.
   */
  const applyBackendResponse = async (data: BackendResponse, fallbackText: string) => {
    const responseData = data?.data
    // Older/newer backend versions may return filters without prebuilt cards.
    // Normalize them here so the UI always has one visible, searchable card.
    const rawFilters = responseData?.filters || {}

    const filterCards: Card[] = Object.entries(rawFilters).length > 0
      ? [{
          type: "filters",
          title: "Narrow Down Your Search",
          options: [],
          groups: Object.entries(rawFilters).map(([name, values]) => ({
            name,
            options: Array.isArray(values) ? values.map(String) : [String(values)],
          })),
          show_search: true,
          search_placeholder: "Search here...",
          submit_button: "Find the Product",
        }]
      : []

    const backendCards: Card[] = Array.isArray(responseData?.cards)
      ? responseData.cards
          .filter((card): card is Card => Boolean(card))
          .map((card) => {
            // Preserve greeting/option cards exactly as returned. Only convert
            // the backend's alternate filter_group shape into the filter-card
            // shape rendered by ChatCards.
            if (card.type !== "filter_group") return card

            return {
              ...card,
              type: "filters",
              groups: card.groups?.length
                ? card.groups
                : Object.entries(rawFilters).map(([name, values]) => ({
                    name,
                    options: Array.isArray(values) ? values.map(String) : [String(values)],
                  })),
              show_search: card.show_search !== false,
              search_placeholder: card.search_placeholder || "Search here...",
              submit_button: card.submit_button || "Find the Product",
            }
          })
      : []

    const cards = backendCards.length > 0 ? backendCards : filterCards
    // Backend may indicate the response "type" either via data.type or a top-level message field.
    const type = responseData?.type || data?.message

    if (type === "parsed_query" || type === "ready") {
      const canonicalProduct = responseData?.canonical_product
      const searchQuery = responseData?.search_query || fallbackText
      const loading = responseData?.loading || {}

      replaceTemporaryMessage({
        role: "assistant",
        content:
          responseData?.message ||
          responseData?.assistant_message ||
          "Finding the best product based on your preferences...",
        canonicalProduct,
        parsedSearchQuery: searchQuery,
        loading,
      });

      if (searchQuery) setActiveProductLabel(searchQuery)

            // Broad exploratory requests may be represented as parsed_query with
      // search_now=false by an older/alternate agent response. Render the
      // filter card and wait for the user instead of scraping immediately.
      if (responseData?.search_now === false) {
        setMessages((prev) => [
          ...prev,
          {
            role: "assistant",
            content: responseData?.message || "Choose a few preferences before I search.",
            filters: rawFilters,
            cards,
            confidence: responseData?.confidence,
          },
        ])
      } else if (canonicalProduct) {
        await handleScrape(searchQuery, canonicalProduct, loading, true)
      }

    } else if (type === "conversation") {
      replaceTemporaryMessage({
        role: "assistant",
        content: responseData?.message || responseData?.assistant_message || "",
        questions: responseData?.questions || [],
        chips: responseData?.chips || [],
        recommendations: responseData?.recommendations || [],
        comparison: responseData?.comparison,
        productLine: responseData?.product_line,
        confidence: responseData?.confidence,
        filters: rawFilters,
        nextAction: responseData?.next_action,
        cards,
      })
    } else if (type === "results") {
      // Backend has already produced final results conversationally (no separate
      // scrape round-trip needed) — render products plus any follow-up prompts.
      const products = normalizeProducts(responseData?.products || [])
      const recommendation = buildDealRecommendation(products)
      setMessages((prev) => [
        ...prev,
        {
          role: "assistant",
          content: [
            responseData?.message || responseData?.assistant_message || "Here are the products I found.",
            recommendation,
          ].filter(Boolean).join("\n\n"),
          products,
          followUps: responseData?.follow_ups || [],
        },
      ])
    } else if (type === "products") {
      // Backend has finished scraping — normalize and render the product cards.
      // The backend now owns the recommendation copy, so we just display its message.
      const products = normalizeProducts(responseData?.products || [])
      const searchQuery = responseData?.search_query || fallbackText
      if (searchQuery) setActiveProductLabel(searchQuery)

      if (products.length === 0) {
        setMessages((prev) => [
          ...prev,
          {
            role: "assistant",
            content: `No products found for ${searchQuery}. Try rephrasing or a different product.`,
          },
        ])
      } else {
        const recommendation = buildDealRecommendation(products)
        setMessages((prev) => [
          ...prev,
          {
            role: "assistant",
            content: [
              responseData?.message || responseData?.assistant_message || `Here are the best prices I found for ${searchQuery}.`,
              recommendation,
            ].filter(Boolean).join("\n\n"),
            products,
            searchQuery,
          },
        ])
      }
    } else {
      // Fallback: unknown/unspecified response type — just show whatever message text exists.
      const message = responseData?.message || responseData?.assistant_message || data?.message || "No response."
      setMessages((prev) => [...prev, { role: "assistant", content: message, cards }])
    }
  }

  const handleSend = async (overrideQuery?: string) => {
    const text = overrideQuery ?? query.trim()
    if (!text || isLoading) return

    const isNewSession = messages.length === 0

    // Freeze any previously-shown clarification option buttons so they can't be clicked again.
    setMessages((prev) => prev.map((m) => (m.role === "assistant" && m.options && !m.optionUsed ? { ...m, optionUsed: true } : m)))

    if (isNewSession) {
      setActiveSession(text)
      setActiveProductLabel(text)
      // Add this as a new recent-search entry, de-duping by case-insensitive query match
      // and capping the list at 9 entries (most recent first).
      setSessions((prev) => {
        const filtered = prev.filter((s) => s.query.toLowerCase() !== text.toLowerCase())
        return [{ query: text, messages: [], filters: {} }, ...filtered.slice(0, 8)]
      })
    }

    // Append the user's message, then show the single rich loading card.
    setMessages((prev) => [...prev, { role: "user", content: text }])

    setQuery("")
    setIsLoading(true)
    const progress = startLoadingProgress(getInitialLoadingContent(text))

    try {
      const data = await searchProducts(text, sessionId)
      await applyBackendResponse(data, text)
      await waitForGreetingLoading(text)
    } catch (error) {
      // The backend may have responded successfully and the failure may be
      // in response parsing or rendering, so preserve the real cause.
      console.error("[Frontend] Search response handling failed:", error)
      setMessages((prev) => [...prev, { role: "assistant", content: "The backend responded, but the result could not be displayed. Check the browser console for details." }])

    } finally {
      stopLoadingProgress(progress)
      setIsLoading(false)
    }
  }

  /**
   * Submits a filter/chip/search-box selection to the backend WITHOUT adding
   * a "user" chat bubble — the person clicked buttons or typed into a filter
   * card, they didn't type a chat message, so the transcript shouldn't show
   * one. The assistant's reply (canonical product / results / follow-up
   * questions) still renders normally.
   *
   * `filters` is optional structured data (e.g. { "Budget": ["Under ₹500"] })
   * sent alongside the human-readable summary text. Your /search endpoint
      * is accepted by the backend and included in the agent context, so the
   * selected options are not lost between the UI and the CrewAI workflow.

   */
  const handleFilterSearch = async (
    text: string,
    filters?: Record<string, string[]>,
  ) => {
    console.log("handleFilterSearch called", text, filters);
    const trimmed = text.trim()
    if (!trimmed || isLoading) return

    const isNewSession = messages.length === 0

    // Freeze any previously-shown clarification option/filter cards so they
    // can't be submitted twice.
    setMessages((prev) =>
      prev.map((m) =>
        m.role === "assistant" && (m.options || m.cards?.length) && !m.optionUsed
          ? { ...m, optionUsed: true }
          : m,
      ),
    )

    if (isNewSession) {
      setActiveSession(trimmed)
      setActiveProductLabel(trimmed)
      setSessions((prev) => {
        const filtered = prev.filter((s) => s.query.toLowerCase() !== trimmed.toLowerCase())
        return [{ query: trimmed, messages: [], filters: filters || {} }, ...filtered.slice(0, 8)]
      })
    }

    // No chat bubble is added for a filter selection; the rich loading card
    // is the only in-progress UI shown here.
    setIsLoading(true)
    const progress = startLoadingProgress(getInitialLoadingContent(trimmed))

    try {
      const data = await searchProducts(trimmed, sessionId, filters)
      // Use the same response-type pipeline as typed messages. A card search
      // can return parsed_query first, which must continue into /scrape; it is
      // not an empty products response.
      await applyBackendResponse(data, trimmed)
      await waitForGreetingLoading(trimmed)
    } catch (error) {
      console.error("[Frontend] Filter response handling failed:", error)
      setMessages((prev) => [...prev, { role: "assistant", content: "The backend responded, but the result could not be displayed. Check the browser console for details." }])

    } finally {
      stopLoadingProgress(progress)
      setIsLoading(false)
    }
  }

  const handleNewSearch = async () => {
      try {
        await clearSession(sessionId)
      } catch (err) {
        console.error("Session clear failed:", err)
      }

      // New session ID includes a random suffix to avoid any timestamp collisions.
      setSessionId(`session_${Date.now()}_${Math.random().toString(36).slice(2)}`)
      setMessages([])
      setQuery("")
      setActiveSession(null)
      setActiveProductLabel(null)
      setLoadingContent({})
      inputRef.current?.focus()
  }

  /**
   * Kicks off the actual scrape — this is the real long wait, so it's where
   * the rich loading bubble (title/description/tip) gets shown. `loading`
   * comes from the message's own `loading` field (set when the parsed_query/
   * ready response arrived), so it matches whatever product is actually
   * being searched for, not whatever was last typed.
   */
  const handleScrape = async (
    searchQuery: string,
    canonicalProduct: CanonicalProduct,
    loading?: LoadingContent,
    allowWhileLoading = false,
  ) => {
      if (isLoading && !allowWhileLoading) return
      const progress = startLoadingProgress({
        title: loading?.title || "Searching for the best matches...",
        description: loading?.description || `We’re checking prices and availability for ${searchQuery}.`,
        tip: loading?.tip || "This can take a moment while we compare products across stores.",
      }, 1)
      setIsLoading(true)

      try {
        const data = await scrapeProducts(
          searchQuery,
          canonicalProduct
        );
        const responseData = data?.data
        const products = normalizeProducts(responseData?.products || [])
        const recommendation = buildDealRecommendation(products)

        setMessages((prev) => [
          ...prev,
          {
            role: "assistant",
            content: [
              responseData?.message || "Here are the products I found.",
              recommendation,
            ].filter(Boolean).join("\n\n"),
            products,
            searchQuery,
          },
        ])
      } catch {
        setMessages((prev) => [...prev, { role: "assistant", content: "Scraping failed." }])
      } finally {
            stopLoadingProgress(progress)
            setIsLoading(false)
        }
      }

  return {
    query,
    setQuery,

    messages,
    setMessages,

    isLoading,
    setIsLoading,

    loadingContent,
    loadingStage,
    
    sessionId,
    setSessionId,

    sessions,
    setSessions,

    activeSession,
    setActiveSession,

    sidebarCollapsed,
    setSidebarCollapsed,

    recentCollapsed,
    setRecentCollapsed,

    activeProductLabel,
    setActiveProductLabel,

    messagesScrollRef,
    inputRef,

    handleSend,
    handleFilterSearch,
    handleProductAction,
    handleNewSearch,
    handleScrape,
  };
}
